### ISSUE TITLE
A few bugs with incorrect casing

### ISSUE THREAD

**Issue by Nogbit** [UWFosterIT/proper-name-case#3]
1. The name of `Debadrita Das` (correct casing) is getting converted to `Debadrita das` (incorrect)
2. The name of `Di Zhang` (correct casing) is getting converted to `di Zhang` (incorrect)

Please update the test scripts and code so that these get converted correctly.

**Comment by kevintechie** [comment]
closed by 18bbf9cb473aa273623c86d25a60924c1617467b
